
id = "VoiceStuff"
name = "VoiceStuff"
description = "Expands the limits on voice pitch and speed in the options menu. Additionally, scrolling on the slider won't make it scroll up and holding shift will increase the granularity."
version = "1.0.1"
homepage = "https://github.com/Awesomerly/VoiceStuff"
author = "Awesomerly"

icon = "icon.png"
readme = "README.md"

[project]
godot = "./project/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"
